name:  Teste de aplicacao

on:
  push:
    branches: [ main ]


jobs:

  unit_testing:
    name: Unitary Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

         # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        working-directory: api
        run: |
          pip install -r requirements.txt
      - name: Run Unitary Tests
        env:
          APP_ENV: test
        run: |
          pytest
